<a href="https://colab.research.google.com/github/manyajsingh/MachineLearning/blob/Personal_ML/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy- numeric python
# ndarray- n dimensional array
# arrays can be sliced like basic lists
import numpy as np
np1= np.array([0,1,2,3,4,5])
print(np1.shape) #(6,) is returned as a single element tuple

np2= np.arange(10)
print(np2)

np3=np.arange(-9,0,2)
print(np3)

np4=np.zeros(5)
print(np4)

np5=np.zeros((2,10)) # a 2 dimensional array with each array consisting of 10 zeroes
print(np5)

np6= np.full((10), 6) # 10 numbers of 6 in an array
print(np6)

np7=np.full((2,10),6) # 2d array with 10 elements, each element being 6
print(np7)

l=[1,2,3,4,5,6,7]
np8= np.array(l)
print(np8) # to convert a list to an array

print(np2[1:5:2])
print(np2[::2])

np9=np.array([[1,2,3,4,5], [11,22,33,44,55], [111,222,333,444,555]])
print(np9[1,2]) # to access the np9[1][2] element
print(np9[0:2, 1:3]) # the first argument specifies the slicing of the number of arrays to  be dealt with
                     # the second argument specifies the slicing within each individual list and will be applied to all the arrays mentioned in the first argument

np10=np.array([-4,-3,-2,-1,0,1,2,3,4])
np11= np.sqrt(np10)
print(np11)
print(np.absolute(np10)) # prints the mod of all elements
print(np.exp(np1))
print(np.max(np10))
print(np.min(np10))
print(np.sign(np10)) # works like signum function (returns -1 for all -ve, 0 for 0, 1 for all +ve)
                     # sin cos tan log can also be performed for all elements in the array (np.sin(np1))


(6,)
[0 1 2 3 4 5 6 7 8 9]
[-9 -7 -5 -3 -1]
[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[6 6 6 6 6 6 6 6 6 6]
[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]
[1 2 3 4 5 6 7]
[1 3]
[0 2 4 6 8]
33
[[ 2  3]
 [22 33]]
[       nan        nan        nan        nan 0.         1.
 1.41421356 1.73205081 2.        ]
[4 3 2 1 0 1 2 3 4]
[  1.           2.71828183   7.3890561   20.08553692  54.59815003
 148.4131591 ]
4
-4
[-1 -1 -1 -1  0  1  1  1  1]


<ipython-input-34-3a9102880505>:39: RuntimeWarning: invalid value encountered in sqrt
  np11= np.sqrt(np10)


In [ ]:
import numpy as np
np1= np.array([1,2,3,4,5])
np2= np1.view()
np3=np1.copy()
np4=np2.copy()
print(f'original np1 {np1}') # f means formatted string literals
print(f'original np2 {np2}')
print(f'original np3 {np3}')
print(f'original np4 {np4}')

np2[0]=41

print(f'original np1 {np1}')
print(f'original np2 {np2}') # whenever we change the original, the view gets changed too
                             # main difference between copy and view
                             # changes made to view are also reflected in original
                             # connected in both ways
print(f'original np3 {np3}')
print(f'original np4 {np4}')

original np1 [1 2 3 4 5]
original np2 [1 2 3 4 5]
original np3 [1 2 3 4 5]
original np4 [1 2 3 4 5]
original np1 [41  2  3  4  5]
original np2 [41  2  3  4  5]
original np3 [1 2 3 4 5]
original np4 [1 2 3 4 5]


In [ ]:
import numpy as np
np1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np1)
print(np1.shape)
np2=np.array([[1,2,3,4,5], [11,22,33,44,55]])
print(np2)
print(np2.shape) # will return dimensions and the number of elements per dimension respectively

# to reshape 2D
np3=np1.reshape(3,4)
print(np3)
 # to reshape 3D
np4=np1.reshape(2,3,2)
print(np4)

# np4=np1.reshape(2,2,2)
# print(np4) would have generated an error as the same number of elements need to be readjusted

np5=np4.reshape(-1) # will reshape the array back to a 1D array
print(np5)
#PS- if the number of total elements are known, reshaping can also be done using the following command
#np5= np4.reshape(total number of elements), in this case,12

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
[[ 1  2  3  4  5]
 [11 22 33 44 55]]
(2, 5)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
import numpy as np
np3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(np3.shape)
for i in np3:
  print(i)
  for j in i:
    print(j)
    for k in j:
      print(k)
# dimension of array= number of for loops required to access each individual element
# short cut:
for i in np.nditer(np3):
  print(i)

(2, 2, 3)
[[1 2 3]
 [4 5 6]]
[1 2 3]
1
2
3
[4 5 6]
4
5
6
[[ 7  8  9]
 [10 11 12]]
[7 8 9]
7
8
9
[10 11 12]
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
import numpy as np
np1=np.array([6,7,4,9,0,22,3])
print(np.sort(np1)) # this comment cannot be given in a single line in the case og a list. will return None
np2=np.array(["John", "Tina", "Aaron", "Zed"])
print(np.sort(np2))
np3=np.array([True, False, False, True])
print(np.sort(np3)) # when we sort, we only change the copy. not the original at all
np4=np.array([[6,7,1,9], [3,5,0,-6]])
print(np.sort(np4)) # sorts the mini arrays within themselves but does not change their indexing

[ 0  3  4  6  7  9 22]
['Aaron' 'John' 'Tina' 'Zed']
[False False  True  True]
[[ 1  6  7  9]
 [-6  0  3  5]]


In [ ]:
l1=[1,33,2,23,3,-22]
l1.sort()
print(l1)
l2=[[23,2,11,876,-66],[34,332,3,-766,877]]
l2.sort()
print(l2) # sorts the nested lists only by the first element, changes the index of the nested lists if needed

[-22, 1, 2, 3, 23, 33]
[[23, 2, 11, 876, -66], [34, 332, 3, -766, 877]]


In [ ]:
import numpy as np
np1=np.array([1,2,3,4,5,6,7,8,9,10,3,13])
x=np.where(np1==3)
print(x) # will return a tuple of the index of wherever the element 3 is present
print(x[0]) # will simply return the index of wherever the element is present
print(np1[x[0]])
print(np1[x])
y=np.where(np1%2==0) # will return the index of wherever an even number is present
print(y[0])

(array([ 2, 10]),)
[ 2 10]
[3 3]
[3 3]
[1 3 5 7 9]


In [ ]:
import numpy as np
np1= np.array([11,12,3,4,5])
x=[True, True, False, False, False]
print(np1[x]) # to filter out np1 according to x (returns the elements, not the indices)
#alternative:
filterodd=[]
for i in np1:
  if i%2 !=0:
    filterodd.append(True)
  else:
    filterodd.append(False)
print(np1)
print(filterodd)
print(np1[filterodd])
#shortcut:
filtereven=(np1%2==0)
print(np1[filtereven])

[11 12]
[11 12  3  4  5]
[True, False, True, False, True]
[11  3  5]
[12  4]
